### ISSUE TITLE
Dataset Features

### ISSUE THREAD

**Issue by AmeenAli** [eric-xw/Video-guided-Machine-Translation#2]
Hello,
I wanted to ask about the possibility of publishing the video frames at least so we can extract other features type (for example Mask-RCNN .. spatial vgg19 ..)
Thanks!

**Comment by eric-xw** [comment]
Hi Ameen,

All the videos in the dataset are Youtube video clips. In the json files, we provide the YouTube IDs with the start and the end times. Due to the legal and privacy concerns, we cannot directly share the downloaded videos in any way (https://vatex.org/main/download.html). But feel free to download these video clips by yourself.

**Comment by AmeenAli** [comment]
@eric-xw Thanks!
But some videos are not available , anything can done to this?
Thanks!
